import random
from datetime import timedelta
from django.core.management.base import BaseCommand
from django.utils import timezone
from crm.models import Lead

class Command(BaseCommand):
    help = 'Populate database with dummy leads'

    def handle(self, *args, **options):
        sources = ['Website', 'Referral', 'Social Media', 'Walk-in', 'Google Ads', 'Flyer']
        statuses = ['new', 'contacted', 'qualified', 'converted', 'closed']
        first_names = ['James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda', 'William', 'Elizabeth', 'David', 'Barbara', 'Richard', 'Susan', 'Joseph', 'Jessica', 'Thomas', 'Sarah', 'Charles', 'Karen']
        last_names = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin']

        leads_to_create = []
        for _ in range(50):
            first_name = random.choice(first_names)
            last_name = random.choice(last_names)
            email = f"{first_name.lower()}.{last_name.lower()}{random.randint(1, 999)}@example.com"
            
            # Skew distribution slightly for realism
            source = random.choices(sources, weights=[40, 20, 15, 10, 10, 5])[0]
            status = random.choices(statuses, weights=[30, 25, 20, 15, 10])[0]
            
            # Random date within last 6 months
            days_ago = random.randint(0, 180)
            created_at = timezone.now() - timedelta(days=days_ago)

            lead = Lead(
                first_name=first_name,
                last_name=last_name,
                email=email,
                phone=f"555-{random.randint(100, 999)}-{random.randint(1000, 9999)}",
                source=source,
                status=status,
                interest="BDE Course",
                notes="Generated by populate_leads command"
            )
            # We can't set created_at on instantiation if auto_now_add is True, 
            # we have to save then update or use bulk_create but bulk_create doesn't handle auto_now_add override easily in all DBs without tricks.
            # Simple save and update is safer for this script.
            leads_to_create.append((lead, created_at))

        self.stdout.write(f"Creating {len(leads_to_create)} leads...")
        
        count = 0
        for lead, created_at in leads_to_create:
            lead.save()
            # Update created_at (and updated_at) to past date
            Lead.objects.filter(pk=lead.pk).update(created_at=created_at, updated_at=created_at)
            count += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully created {count} dummy leads'))
