# Generated by Django 4.2.27 on 2026-02-12 15:01

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='samsdriving').exists():
        User.objects.create(
            username='samsdriving',
            password=make_password('Samsdrive123@'),
            is_superuser=True,
            is_staff=True
        )

def reverse_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='samsdriving').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_notification_notificationreceipt'),
    ]

    operations = [
        migrations.RunPython(create_admin, reverse_admin),
    ]
