# Generated by Django 4.2.27 on 2026-02-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarAccount',
        ),
    ]
