# Generated by Django 4.2.27 on 2026-02-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_blog_summary_ckeditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
