# Generated by Django 4.2.27 on 2026-03-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_calendaraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/courses/'),
        ),
    ]
