# Generated by Django 4.2.27 on 2026-03-14 18:48

from django.db import migrations, models


def seed_home_hero_slides(apps, schema_editor):
    HomeHeroSlide = apps.get_model("crm", "HomeHeroSlide")
    if HomeHeroSlide.objects.exists():
        return
    HomeHeroSlide.objects.create(
        title_line_1="Are You Looking",
        title_line_2="to learn",
        title_line_3="Driving?",
        layer_asset="assets/images/backgrounds/slider-1-layer-1.png",
        display_order=0,
        is_active=True,
    )
    HomeHeroSlide.objects.create(
        title_line_1="Are You Looking",
        title_line_2="for a Car for the",
        title_line_3="Driving Test?",
        layer_asset="assets/images/backgrounds/slider-1-layer-2.png",
        display_order=1,
        is_active=True,
    )
    HomeHeroSlide.objects.create(
        title_line_1="Are You Looking",
        title_line_2="to master",
        title_line_3="Driving?",
        layer_asset="assets/images/backgrounds/slider-1-layer-3.png",
        display_order=2,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(max_length=120)),
                ('title_line_2', models.CharField(blank=True, max_length=120)),
                ('title_line_3', models.CharField(blank=True, max_length=120)),
                ('button_text', models.CharField(default='View Courses', max_length=60)),
                ('button_url', models.CharField(blank=True, max_length=300)),
                ('background_image', models.ImageField(blank=True, upload_to='upload/hero/')),
                ('background_asset', models.CharField(blank=True, default='assets/images/backgrounds/slider-1-1.png', max_length=255)),
                ('layer_image', models.ImageField(blank=True, upload_to='upload/hero_layers/')),
                ('layer_asset', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-updated_at'],
            },
        ),
        migrations.RunPython(seed_home_hero_slides, migrations.RunPython.noop),
    ]
