# Generated by Django 4.2.27 on 2026-03-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_homeheroslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='course',
            name='policies',
        ),
    ]
