# Generated by Django 4.2.30 on 2026-09-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_remove_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ga_client_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ga_purchase_reported',
            field=models.BooleanField(default=False),
        ),
    ]
